#include <stdlib.h>
#include <stdio.h>

//prototipagem
int verificarNumero(int max);
//int menuPrincipal(LISTA_SENSOR* listaSensor, DISTANCIAS_LISTA* listaDistancias, PASSAGEM_LISTA* listaPassagem, LISTA_CARRO* listaCarro, LISTA_DONOS* listaDonos);
void menuDistancias(DISTANCIAS_LISTA* listaDistancias);
void menuPassagens(PASSAGEM_LISTA* listaPassagens, LISTA_HASHC* listaHashCarros);
void menuSensores(LISTA_SENSOR* listaSensores);
//void menuCarros(LISTA_CARRO* listaCarros, LISTA_DONOS* listaDonos);
//void menuDonos(LISTA_DONOS* listaDonos);
