#include <stdio.h>
#include <stdlib.h>


int calcularTamanhoEDSensor(LISTA_SENSOR* lista);
int calcularTamanhoEDDistancia(DISTANCIAS_LISTA* lista);
int calcularTamanhoEDPassagem(PASSAGEM_LISTA* lista);

//******************** ERRO QUANDO DOU PROTOT ******************************
//int calcularTamanhoEDDonos(LISTA_DONOS* lista);
//int calcularTamanhoEDCarro(LISTA_HASHC* listaHash)
//void memoriaTotalOcupadaED(LISTA_SENSOR* listaS, DISTANCIAS_LISTA* listaD, PASSAGEM_LISTA* listaP, LISTA_CARRO* listaC);
//int inicializarED(LISTA_SENSOR* listaSensor, DISTANCIAS_LISTA* listaDistancias, PASSAGEM_LISTA* listaPassagem, LISTA_CARRO* listaCarro);
